export const breakpointTexts = {
  shell: {
    title: 'Breakpoints',
    closeAria: 'Close',
  },
  defaultFormName: 'Pause API request',
  defaultPathRegex: '/api/',
  defaultRuleName: 'Breakpoint',
  /** New breakpoint name from override/traffic: Pause <name> */
  pauseName: (name: string) => `Pause ${name}`,
  nameLabel: 'Name',
  methodLabel: 'Method',
  methodPlaceholder: 'GET',
  originLabel: 'Origin',
  pathRegexLabel: 'Path',
  originPlaceholder: 'https://example.com',
  pathPlaceholder: '/api/',
  add: 'Add breakpoint',
  saveChanges: 'Save changes',
  saveHint: 'Press Cmd/Ctrl + S to save',
  newBreakpoint: 'New breakpoint',
  noneYet: 'No breakpoints yet.',
  selectHint: 'Select a breakpoint from the list, or create a new one.',
  newTitle: 'New breakpoint',
  detailTitle: 'Breakpoint',
  toggleHostGroup: (origin: string) => `Show or hide breakpoints for ${origin}`,
  matchSection: 'Match',
  anyValue: '∗',
  disabledPill: 'disabled',
  saving: 'Saving…',
  duplicateIdentity: 'A breakpoint with the same method, origin, and path already exists.',
  createFailed: (status: number) => `Create failed (HTTP ${status})`,
  updateFailed: (status: number) => `Update failed (HTTP ${status})`,
  enable: 'Enable',
  disable: 'Disable',
  moreActions: 'More breakpoint actions',
  enableAll: 'Enable all',
  disableAll: 'Disable all',
  delete: 'Delete',
  deleteConfirm: 'Delete this breakpoint rule?',
  continueRequest: 'Continue request',
  continueAllFromBreakpoint: 'Continue from this breakpoint',
} as const
