export const trafficTexts = {
  clear: 'Clear',
  filterPlaceholder: 'Type keyword and press Enter…',
  removeKeywordAriaLabel: (keyword: string) =>
    `Remove filter keyword ${keyword}`,
  filter: {
    buttonTooltip: 'Filter',
    buttonAriaLabel: 'Open traffic filters',
    activeBadgeAriaLabel: 'Filters active',
    dialogTitle: 'Filters',
    dialogDescription:
      'Filter traffic by resource type, request method, response status, and requester app.',
    clearAll: 'Clear all',
    close: 'Close',
    groupResourceType: 'Resource type',
    groupMethod: 'Request method',
    groupStatus: 'Status code',
    groupRequesterApp: 'Requester app',
    resourceTypeLabels: {
      document: 'Document',
      js: 'JS',
      css: 'CSS',
      image: 'Image',
      video: 'Media',
      font: 'Font',
      wasm: 'Wasm',
      json: 'JSON',
      other: 'Other',
    } as Record<string, string>,
    methodLabels: {
      GET: 'GET',
      POST: 'POST',
      PUT: 'PUT',
      DELETE: 'DELETE',
      PATCH: 'PATCH',
      OPTIONS: 'OPTIONS',
      HEAD: 'HEAD',
      WEBSOCKET: 'WebSocket',
    } as Record<string, string>,
    statusClassLabels: {
      '1xx': '1xx',
      '2xx': '2xx',
      '3xx': '3xx',
      '4xx': '4xx',
      '5xx': '5xx',
    } as Record<string, string>,
    requesterAppLabels: {} as Record<string, string>,
  },
  schemeHttps: 'HTTPS',
  connectTunnel: (url: string) => `${url} (TLS tunnel)`,
  connectMitmBypassed: (url: string) => `${url} (MITM bypassed, TLS tunnel)`,
  connectMitmHandshakeFailed: (url: string) => `${url} (MITM handshake failed)`,
  mitmHandshakeNote:
    'MITM: the client did not complete TLS to the proxy-issued certificate (pinning, unknown CA, or aborted connection).',
  mitmBypassedNote:
    'MITM was skipped for this host after a previous handshake failure. The CONNECT tunnel is shown, but encrypted paths and bodies are not visible.',
  tagPending: 'PEND',
  tagError: 'ERR',
  tagBypassed: 'BYPS',
  sectionRequest: 'Request',
  sectionResponse: 'Response',
  closeDetail: 'Close detail',
  saveRequest: 'Save request',
  requestSaved: 'Saved',
  copyCurl: 'Copy cURL',
  copyCurlSuccess: 'Copied cURL',
  copyCurlFailed: (detail: string) => `Could not copy cURL: ${detail}`,
  copyUrlSuccess: 'Copied URL',
  copyUrlFailed: (detail: string) => `Could not copy URL: ${detail}`,
  rowMenuOpen: 'Actions',
  rowMenuCopyCurl: 'Copy cURL',
  rowMenuSaveRequest: 'Save request',
  rowMenuOpenSavedRequest: 'Open saved request',
  rowMenuOverride: 'Override response',
  rowMenuViewMatchedOverride: 'View matched override',
  rowMenuAddBreakpoint: 'Add breakpoint',
  rowMenuViewMatchedBreakpoint: 'View matched breakpoint',
  rowMenuReplay: 'Replay request',
  backToTop: 'Top',
  focusSelected: 'Focus selected',
  replayRequestSuccess: 'Replay sent',
  replayRequestFailed: (detail: string) => `Replay failed: ${detail}`,
  addBreakpoint: 'Add breakpoint',
  viewMatchedOverride: 'View matched override',
  viewMatchedBreakpoint: 'View matched breakpoint',
  resuming: 'Resuming…',
  resume: 'Resume',
  overrideResponse: 'Override response',
  pendingAtBreakpoint: (breakpointName: string | null) =>
    `Pending at breakpoint${breakpointName ? `: ${breakpointName}` : ''}. The client is waiting for you to resume this request.`,
  connectNote:
    'HTTPS uses a CONNECT tunnel; paths and bodies inside TLS are not visible to the proxy.',
  noResponseYet:
    'No response yet because this request is paused before override or upstream handling.',
  streamBodyNoPreview:
    'Streaming response — body fills in as chunks arrive (retained up to ~64 MB for the dashboard).',
  streamBodyHint:
    'Full streamed body retained for this view (up to ~64 MB). Updates while the connection stays open; the last chunk is shown when the stream ends.',
  body: 'Body',
  empty: {
    p1a: 'every HTTP request',
    p1b: 'every HTTPS CONNECT tunnel',
    p1c:
      'that clients send through this proxy. Only traffic routed via HTTP_PROXY/ HTTPS_PROXY or a system proxy appears here — not other programs on the machine.',
    p2a: 'Select a row, use',
    p2b: 'Test proxy',
    p2c: ', or point a client at the proxy (browsers need OS proxy settings or an extension; shell',
    p2d: 'export',
    p2e: 'alone does not affect them).',
  },
  clientMeta: (peer: string, kind: string, scheme: string, duration: string) =>
    `client ${peer} · ${kind} · ${scheme} · ${duration}`,
} as const
