export const floatingTrafficTexts = {
  title: 'Traffic',
  subtitle: '悬浮模式',
  filterPlaceholder: 'Type keyword and press Enter…',
  removeKeywordAriaLabel: (keyword: string) =>
    `Remove filter keyword ${keyword}`,
  clear: 'Clear traffic',
  empty: 'No traffic yet',
  tagError: 'ERR',
  tagBypassed: 'BYPASS',
  tagPending: 'WAIT',
  detailTitle: 'Request detail',
  detailUrl: 'URL',
  detailRequestBody: 'Request body',
  detailResponse: 'Response',
  detailNoResponse: 'No response yet',
  detailNoBody: 'No response body',
  copyCurl: 'Copy cURL',
  copyCurlSuccess: 'Copied cURL',
  copyCurlFailed: (detail: string) => `Could not copy cURL: ${detail}`,
  openMainWindow: 'Open main window',
  openMainFailed: (detail: string) => `Could not open main window: ${detail}`,
} as const
