export const overrideEditorTexts = {
  form: {
    defaultOverrideName: 'Override',
  },
  shell: {
    title: 'Override response',
    subtitle:
      'Future requests that match the rule receive this response (plain HTTP; first matching rule wins).',
    closeAria: 'Close',
    fabRequest: 'Request',
    fabDrag: 'Drag to move',
    footResumeRequest: 'Resume request',
    footResuming: 'Resuming…',
    footAddBreakpoint: 'Add breakpoint',
    footCancel: 'Cancel',
    saveChanges: 'Save changes',
    saveOverride: 'Save override',
  },
  files: {
    newRule: 'New rule',
    importHint:
      'Body import/export applies to the rule you are editing in the center editor. Click a card in the list below to switch to another rule.',
    importToBody: 'Import to body',
    exportBody: 'Export body',
    clearBody: 'Clear body',
    listIntroLead: 'Rule list (SQLite). You can also add a rule from',
    listIntroOr: ', or',
    listIntroAbove: 'above, then use',
    listIntroTail: 'to fill match and body.',
    noRulesLead: 'No rules yet. Use',
    noRulesTail: 'or open one from captured traffic.',
    openRule: (name: string) => `Open rule: ${name}`,
    deleteRule: 'Delete rule',
    deleteRuleConfirm: 'Delete this override from SQLite?',
    overrideId: 'Override id:',
    httpStatus: (n: number) => `HTTP ${n}`,
    streamed: (ms: number) =>
      `Streamed: ${ms} ms between chunks (body split on blank lines)`,
    streamBodyLabel: 'Stream body content',
    responseBodyLabel: 'Response body content',
    reset: 'Reset',
    saveContent: 'Save content',
    saving: 'Saving…',
    enable: 'Enable',
    disable: 'Disable',
    disabled: 'disabled',
  },
  request: {
    name: 'Name',
    enableRule: 'Enable this override rule',
    matchMethod: 'Match method',
    matchMethodPlaceholder: 'GET',
    host: 'Host contains',
    path: 'Path',
    status: 'Status',
    responseHeaders: 'Response headers (one',
    codeName: 'Name: value',
    perLine: 'per line)',
    streamHint:
      'Stream body (double newline = chunk;',
    eventStream: 'in headers)',
    chunkInterval: 'Interval between chunks (ms)',
    streamController: 'Stream controller',
    play: 'Play',
    stop: 'Stop',
    statusUpdating: 'Updating stream controller...',
    statusPausedDetail:
      'Request is paused. Press Play to start streaming the override response.',
    statusStreaming: 'Streaming. Press Stop to pause after the current chunk.',
    statusPaused: 'Paused. Press Play to continue.',
  },
  monaco: {
    stream: 'Stream: separate chunks with a blank line in the source.',
    body: 'Response body (override)',
  },
} as const
