export const overrideEditorTexts = {
  shell: {
    title: 'Override response',
    closeAria: 'Close',
    fabRequest: 'Request',
    fabDrag: 'Drag to move',
    footResumeRequest: 'Resume request',
    footResuming: 'Resuming…',
    footAddBreakpoint: 'Add breakpoint',
    footCancel: 'Cancel',
    saveChanges: 'Save changes',
    saveOverride: 'Save override',
  },
  files: {
    newRule: 'New rule',
    importHint:
      'Body import/export applies to the rule you are editing in the center editor. Click a card in the list below to switch to another rule.',
    importToBody: 'Import to body',
    exportBody: 'Export body',
    listIntroLead: 'Rule list (SQLite). You can also add a rule from',
    listIntroOr: ', or',
    listIntroAbove: 'above, then use',
    listIntroTail: 'to fill match and body.',
    noRulesLead: 'No rules yet. Use',
    noRulesTail: 'or open one from captured traffic.',
    openRule: (label: string) => `Open rule: ${label}`,
    toggleHostGroup: (host: string) => `Show or hide rules for ${host}`,
    deleteRule: 'Delete rule',
    deleteRuleConfirm: 'Delete this override from SQLite?',
    saving: 'Saving…',
    enable: 'Enable',
    disable: 'Disable',
  },
  request: {
    enableRule: 'Enable this override rule',
    matchIdLabel: 'Override id (SHA-256 of match fields)',
    matchIdDrift:
      'Differs from saved id until you save; changing match fields changes the id.',
    method: 'Method',
    methodHint: 'GET / POST etc; leave empty to match any method',
    protocol: 'Protocol',
    protocolHint: 'http or https; leave empty to match any',
    host: 'Hostname',
    hostHint:
      'Required. Supports exact host or wildcard (*, ?) such as *.example.com or api-?.example.com.',
    hostRequired: 'Hostname is required: set an exact host or wildcard pattern.',
    duplicateMatchIdentity:
      'An override with the same match identity already exists (duplicate id). Change match fields to produce a different id, or open the existing rule from the list.',
    saveIdConflict:
      'Could not save: another rule already uses this id.',
    saveSucceeded: 'Override saved successfully.',
    path: 'Path',
    pathHint:
      'Path only, no query string; leave empty to match any path. Supports wildcard (*, ?).',
    matchHeaders: 'Request headers to match',
    matchHeadersHelp:
      'Name: value per line, or add rows. Empty = match all requests (ignore header matching).',
    addHeaderRow: 'Add header',
    matchQuery: 'Search parameters to match',
    matchQueryHelp: 'Empty = match all. Each key must appear on the request with the given value.',
    addQueryRow: 'Add parameter',
    matchBody: 'Request body to match',
    matchBodyHelp: 'Empty = any body. When set, must match the full request body (UTF-8).',
    enableMapRemote: 'Enable map remote',
    mapRemoteProtocol: 'Map remote protocol',
    mapRemoteHost: 'Map remote host',
    mapRemotePath: 'Map remote path',
    mapRemoteRuleHint:
      'Optional forwarding rule. When protocol + host are set, matched requests are forwarded to that target. Use path * to keep the incoming path.',
    status: 'Status',
    responseHeaders: 'Response headers (one',
    codeName: 'Name: value',
    perLine: 'per line)',
    streamHint:
      'Stream body (double newline = chunk;',
    eventStream: 'in headers)',
    chunkInterval: 'Interval between chunks (ms)',
    streamController: 'Stream controller',
    play: 'Play',
    stop: 'Stop',
    statusUpdating: 'Updating stream controller...',
    statusPausedDetail:
      'Request is paused. Press Play to start streaming the override response.',
    statusStreaming: 'Streaming. Press Stop to pause after the current chunk.',
    statusPaused: 'Paused. Press Play to continue.',
  },
  monaco: {
    stream: 'Stream: separate chunks with a blank line in the source.',
    body: 'Response body (override)',
    imageBody: 'Image response (preview)',
    imageAlt: (mime: string) => `Override response preview (${mime})`,
    imagePreviewUnavailable:
      'Cannot preview: use a data URL or base64 in the body, or import an image file.',
    languageLabel: (lang: string) => `Syntax: ${lang}`,
    beautify: 'Beautify',
    uglify: 'Uglify',
    formatFailed: 'Format failed',
  },
} as const
