export const requestComposerTexts = {
  title: 'Request Composer',
  sections: {
    target: '1. Target',
    request: '2. Request',
    headers: '3. Headers',
    response: 'Response',
    history: 'History',
  },
  fields: {
    url: 'URL',
    method: 'Method',
    searchParams: 'Search params',
    body: 'Body',
    headers: 'Headers',
    historySearch: 'Search history',
  },
  placeholders: {
    url: 'https://api.example.com/api/users',
    keyValueLines: 'key=value',
    headers: 'content-type=application/json',
    body: '{\n  "name": ""\n}',
    historySearch: 'Search method, URL, status…',
  },
  actions: {
    send: 'Send request',
    sending: 'Sending…',
    loadMore: 'Load more',
    reuse: 'Reuse',
    delete: 'Delete',
  },
  emptyHistory: 'No composed requests yet.',
  noResponse: 'Send a request to see the response preview.',
  sentSuccess: 'Request sent',
  sentFailed: (detail: string) => `Request failed: ${detail}`,
  historyLoadFailed: (detail: string) => `Could not load history: ${detail}`,
  historyDeleted: 'History item deleted',
  historyCleared: 'History cleared',
} as const
