export const requestComposerTexts = {
  title: 'Request Composer',
  sections: {
    target: '1. Target',
    request: '2. Request',
    headers: '3. Headers',
    response: 'Response',
    history: 'History',
  },
  fields: {
    url: 'URL',
    method: 'Method',
    searchParams: 'Search params',
    body: 'Body',
    headers: 'Headers',
    historySearch: 'Search history',
  },
  placeholders: {
    url: 'https://api.example.com/api/users',
    keyValueLines: 'key=value',
    headers: 'content-type=application/json',
    body: '{\n  "name": ""\n}',
    historySearch: 'Search method, URL, status…',
  },
  actions: {
    send: 'Send request',
    sending: 'Sending…',
    loadMore: 'Load more',
    reuse: 'Reuse',
    delete: 'Delete',
    saveRequest: 'Save request',
    createOverride: 'Create override',
    importCurl: 'Import cURL',
    cancel: 'Cancel',
    confirmImportCurl: 'Import',
  },
  curlImportDialog: {
    title: 'Import cURL',
    description: 'Paste a curl command to fill the request form automatically.',
    inputLabel: 'cURL command',
    placeholder: "curl 'https://api.example.com/users' -H 'accept: application/json'",
  },
  emptyHistory: 'No composed requests yet.',
  noResponse: 'Send a request to see the response preview.',
  sentSuccess: 'Request sent',
  curlImportSuccess: 'cURL imported',
  curlImportInvalid: 'Please paste a curl command.',
  curlImportMissingUrl: 'Could not find a valid URL in the curl command.',
  curlImportUnclosedQuote: 'The curl command has an unclosed quote.',
  curlImportMissingOptionValue: (option: string) =>
    `Missing value for curl option ${option}.`,
  curlImportInvalidHeader: (value: string) =>
    `Invalid header "${value}". Expected "Name: value".`,
  curlImportFailed: (detail: string) => `Could not import cURL: ${detail}`,
  sentFailed: (detail: string) => `Request failed: ${detail}`,
  historyLoadFailed: (detail: string) => `Could not load history: ${detail}`,
  historyDeleted: 'History item deleted',
  historyCleared: 'History cleared',
} as const
