/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HealthRouteImport } from './routes/health'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WebhooksPaymentRouteImport } from './routes/webhooks/payment'
import { Route as LocalFreeLicenseRouteImport } from './routes/local/free-license'
import { Route as LicensesManualRouteImport } from './routes/licenses/manual'
import { Route as LicensesLicenseIdRouteImport } from './routes/licenses/$licenseId'

const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhooksPaymentRoute = WebhooksPaymentRouteImport.update({
  id: '/webhooks/payment',
  path: '/webhooks/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalFreeLicenseRoute = LocalFreeLicenseRouteImport.update({
  id: '/local/free-license',
  path: '/local/free-license',
  getParentRoute: () => rootRouteImport,
} as any)
const LicensesManualRoute = LicensesManualRouteImport.update({
  id: '/licenses/manual',
  path: '/licenses/manual',
  getParentRoute: () => rootRouteImport,
} as any)
const LicensesLicenseIdRoute = LicensesLicenseIdRouteImport.update({
  id: '/licenses/$licenseId',
  path: '/licenses/$licenseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/licenses/$licenseId': typeof LicensesLicenseIdRoute
  '/licenses/manual': typeof LicensesManualRoute
  '/local/free-license': typeof LocalFreeLicenseRoute
  '/webhooks/payment': typeof WebhooksPaymentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/licenses/$licenseId': typeof LicensesLicenseIdRoute
  '/licenses/manual': typeof LicensesManualRoute
  '/local/free-license': typeof LocalFreeLicenseRoute
  '/webhooks/payment': typeof WebhooksPaymentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/licenses/$licenseId': typeof LicensesLicenseIdRoute
  '/licenses/manual': typeof LicensesManualRoute
  '/local/free-license': typeof LocalFreeLicenseRoute
  '/webhooks/payment': typeof WebhooksPaymentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/licenses/$licenseId'
    | '/licenses/manual'
    | '/local/free-license'
    | '/webhooks/payment'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/licenses/$licenseId'
    | '/licenses/manual'
    | '/local/free-license'
    | '/webhooks/payment'
  id:
    | '__root__'
    | '/'
    | '/health'
    | '/licenses/$licenseId'
    | '/licenses/manual'
    | '/local/free-license'
    | '/webhooks/payment'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HealthRoute: typeof HealthRoute
  LicensesLicenseIdRoute: typeof LicensesLicenseIdRoute
  LicensesManualRoute: typeof LicensesManualRoute
  LocalFreeLicenseRoute: typeof LocalFreeLicenseRoute
  WebhooksPaymentRoute: typeof WebhooksPaymentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhooks/payment': {
      id: '/webhooks/payment'
      path: '/webhooks/payment'
      fullPath: '/webhooks/payment'
      preLoaderRoute: typeof WebhooksPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local/free-license': {
      id: '/local/free-license'
      path: '/local/free-license'
      fullPath: '/local/free-license'
      preLoaderRoute: typeof LocalFreeLicenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licenses/manual': {
      id: '/licenses/manual'
      path: '/licenses/manual'
      fullPath: '/licenses/manual'
      preLoaderRoute: typeof LicensesManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licenses/$licenseId': {
      id: '/licenses/$licenseId'
      path: '/licenses/$licenseId'
      fullPath: '/licenses/$licenseId'
      preLoaderRoute: typeof LicensesLicenseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HealthRoute: HealthRoute,
  LicensesLicenseIdRoute: LicensesLicenseIdRoute,
  LicensesManualRoute: LicensesManualRoute,
  LocalFreeLicenseRoute: LocalFreeLicenseRoute,
  WebhooksPaymentRoute: WebhooksPaymentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
